/*Program handles divide by zero exception with catch all */
#include<iostream>
using namespace std;
int main()
{
	int a,b;
	cout<<"enter a and b values:"<<endl;
	cin>>a>>b;
	cout<<"a is :"<<a<<endl;
	cout<<"b is:"<<b<<endl;
	try
	{
		if(b==0)
		{
			throw b;
		}
		else if(b<0)
		{
			throw "b cannot be negative";
		}
		else
		{
			cout<<"the result of a/b is:"<<a/b<<endl;
		}
	}
	catch(int b)
	{
		cout<<"b cannot be zero"<<endl;
	}
	catch(...)
	{
		cout<<"unknown exception occured,check!!"<<endl;
	}
	return 0;
}
